# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='profile_image',
        ),
    ]
